### ISSUE TITLE
 Incompat with More company

### ISSUE THREAD

**Issue by mmiinnaa11** [DiFFoZ/LethalPerformance#10]
More company now lets you change your cosmetics in-game but having Lethal Performance makes it so you can't see your character when doing so
![image](https://github.com/user-attachments/assets/62464618-58b9-4ab3-9962-9f8941801e7a)
![image](https://github.com/user-attachments/assets/8ca96e84-4b54-40b6-94b3-599dd27633ff)

**Comment by mmiinnaa11** [comment]
Here is how it looks like without lethal performance
![image](https://github.com/user-attachments/assets/73d7b8d2-83c7-4c84-a2b8-f64db162427e)

**Comment by DiFFoZ** [comment]
Fixed in 0.4.3
