### ISSUE TITLE
Can it be compatible with Loadstone? Combining the LS and LethalPerformance is a great optimization combination.

### ISSUE THREAD

**Issue by NakiriFox** [DiFFoZ/LethalPerformance#6]
[Error  : Loadstone(Harmony)] The assembly "LethalPerformance" has patched the method "Void Start()" with a transpiler using "System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction] ReplaceFindObjectOfTypeTranspiler(System.Collections.Generic.IEnumerable`1[HarmonyLib.CodeInstruction])", which we also modify. Unexpected behaviour may occur

[Warning: Loadstone(Harmony)] The assembly "HDLethalCompanyRemake" has patched the method "Void GenerateNewFloor()" with a prefix using "Void RoundPostFix()", which we also modify. Unexpected behaviour may occur

**Comment by DiFFoZ** [comment]
Hi, yes it is compatible with Loadstone

**Comment by NakiriFox** [comment]
thanks :)
