### ISSUE TITLE
[BUG] Remove "Auto force disabling volumetric fog if the hardware system doesn't support it." introduced in V0.4.0

### ISSUE THREAD

**Issue by MiraakThuri** [DiFFoZ/LethalPerformance#9]
Hey, i run the game on a GTX 750 TI, which does not support the modern unity volumetric fog
however, if it's forcefully disabled as in v0.4.0 it also completly break the color palette/athmosphere, making it look really bad
So i think this should actually be removed, or at least togglable

Here is how the game is supposed to look even without correct Volumetric Fog support:
![Lethal Company 2024-10-22 07-16-59-93](https://github.com/user-attachments/assets/6ae97d85-1118-4a6f-a6c9-19579d12403f)

With Volumetric Fog forced off:
![Lethal Company 2024-10-22 07-12-18-82](https://github.com/user-attachments/assets/32c80a94-686f-4bdd-aa3f-de5edf18917a)
![Lethal Company 2024-10-22 07-14-25-30](https://github.com/user-attachments/assets/8d0c388b-35c3-4354-bf95-f642e622082c)

On foggy weather, it's even worse

**Comment by DiFFoZ** [comment]
I don't think that auto force disabling volumetric fog will be removed, because unity spams error about that causing not able to read the logs.

**Comment by MiraakThuri** [comment]
To be fair, most of the hardware concerned, will also get the log spam of "ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed." by default (unless turning gfx-enable-gfx-jobs to 0 but this reduces performance), so i ended up disabling log on my system
Ill stay on 0.3.5 for now, but thx for the answer
